[package]
name = "latency-book-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.3.19", features = ["derive"] }
reqwest = "0.11.14"
tokio = { version = "1", features = ["full"] }
