[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.1"
anyhow = "1.0.69"
env_logger = "0.10.0"
libsql-client = "0.24.4"
tokio = { version = "1", features = ["full"] }
url = "2.3.1"
